#coding:utf-8

PIC_CODE_EXPIRES_SECONDS = 180
SMS_CODE_EXPIRES_SECONDS = 300
SESSION_EXPIRES_SECONDS = 86400
QINIU_URL_PREFIX = "http://olymmyzny.bkt.clouddn.com/"
QINIU_URL_SUFFIX = "?imageMogr2/auto-orient/thumbnail/x220/blur/1x0/quality/75|imageslim"
REDIS_AREA_INFO_EXPIRES_SECONDES = 86400
REDIS_HOUSE_INFO_EXPIRES_SECONDES = 86400
HOME_PAGE_MAX_HOUSES = 5
HOUSE_LIST_PAGE_CACHE_NUM = 2
HOME_PAGE_DATA_REDIS_EXPIRE_SECOND = 7200
HOUSE_LIST_PAGE_CAPACITY = 2